apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoketest-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smoketest-exporter
  template:
    metadata:
      labels:
        app: smoketest-exporter
    spec:
      containers:
      - name: smoketest-exporter
        image: bisdock/smoketest-exporter:latest # Replace with the correct image name
        ports:
        - containerPort: 8000
