global:
  scrape_interval: 15s  # Set scrape interval to 15 seconds

scrape_configs:
  - job_name: 'smoketests'
    static_configs:
      - targets: ['smoketest-exporter:8000']  # Target where the smoketests are exposed

rule_files:
  - "alerting_rules.yml"  # Path to your alerting rules file
